#!/usr/bin/env bash
# Displays information for the specified or all subdomain(s)
fun () {
	local dig_output=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1)
	local rec=$(echo "$dig_output" | awk 'NR==1 {print $4}')
	local dest=$(echo "$dig_output" | awk 'NR==1 {print $5}')
	echo "The subdomain $2 is a $rec record and points to $dest"
}

if [ "${2}" ]; then
	fun "${1}" "${2}"
else
	fun "${1}" www
	fun "${1}" lb-01
	fun "${1}" web-01
	fun "${1}" web-02
fi
