#!/usr/bin/env bash
# Installs and configures HAproxy on a server
apt -y update
apt -y upgrade
apt -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt -y install haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.old
echo "frontend web-frontend
	bind *:80
	default_backend web-backend
backend web-backend
	balance roundrobin
	server web-01 18.234.106.203:80
	server web-02 54.236.12.250:80" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
